version: "3"

services:
  template-api:
    container_name: template-api
    image: ruhyadi/template-api:v1.0.0
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    command: python src/main.py service=api