FROM python:3.9.16-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends\
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt

# Working directory
WORKDIR /app

# Copy the application
COPY . /app

# Run the application
CMD ["bash"]